# Generated by Django 3.1.1 on 2020-10-01 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='tag',
            new_name='tags',
        ),
    ]
